create database users;  

USE users;

CREATE TABLE users(id INT(11) AUTO_INCREMENT PRIMARY KEY, 
	name VARCHAR(100) DEFAULT NULL, 
	email VARCHAR(100) DEFAULT NULL,
	username VARCHAR(30) DEFAULT NULL, 
	password VARCHAR(100) DEFAULT NULL,
	register_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);